# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
    routing_loader: false
#        default_format: json
#        include_format: false
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            CaRMen\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
#    routing_loader: false
#      default_format: json
#      include_format: false
    body_listener: true
    format_listener:
      enabled: true
      rules:
        - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: true}
        - { path: '^/', priorities: ['html'], fallback_format: html, prefer_extension: true}
    param_fetcher_listener: true
#    access_denied_listener:
#      json: true
    view:
      view_response_listener: 'force'
      formats:
        json: true

