
services:
  web:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./docker/nginx/conf/:/etc/nginx/conf.d:ro
      - ./docker/nginx/certs/:/etc/nginx/ssl
      - .:/var/www/html
    depends_on:
      - php
  php:
    container_name: ${PHP_HOST}
    build:
      context: docker/php
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - .:/var/www/html
#      - ./var/log/dev.log:/var/log/dev.log
    working_dir: "${WORKING_DIR}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - "./var/db/mysql:/var/lib/mysql"
            
