# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    maintenance_mode: '%env(bool:MAINTENANCE_MODE)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    CaRMen\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    # This line will pass the 'maintenance_mode' parameter to the constructor of MaintenanceModeListener
    CaRMen\EventListener\MaintenanceModeListener:
        arguments:
            $maintenanceMode: '%maintenance_mode%'

    CaRMen\Security\PermissionChecker:
        arguments:
            $strategies: !tagged_iterator app.permission_strategy

    CaRMen\Security\PermissionStrategyInterface:
        tags: ['app.permission_strategy']
        autoconfigure: false

    CaRMen\Security\Strategy\:
        resource: '../src/Security/Strategy/*'
        tags: ['app.permission_strategy']
        autowire: true
        autoconfigure: false
